### ISSUE TITLE
Add new admin for this repo

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/library-sql#19]
Hi @tracykteal - can you also please add @c-martinez as an admin on this repo?

**Comment by tracykteal** [comment]
what permissions do they need? Admin can only be granted to the whole organization.

**Comment by weaverbel** [comment]
@tracykteal Uh oh - I didn't realise that. We've had people put up their hands to be lesson maintainers - have emailed you about who for what - I thought you could make it repository-specific. How can we make it work ?

**Comment by tracykteal** [comment]
Sorry, it's Owner that's the issue. Admin can be done per repo. I'll set that up.

**Comment by tracykteal** [comment]
They've been sent an invitation to join the 'library' team. Once accepted, that will give them admin access to that repo.

**Comment by weaverbel** [comment]
Thanks @tracykteal ! As you can see, we got a lot done !

**Comment by tracykteal** [comment]
Yes, it was fantastic to see all the work and commits!!

+💯

**Comment by c-martinez** [comment]
Hi @tracykteal -- I should have received an email to join the 'library' team? I've checked my inbox, but I don't seem to be able to find it. Could you perhaps send it again?

**Comment by weaverbel** [comment]
My bad @tracykteal as @c-martinez was not in my original email to you - please add as admin on SQL repo

**Comment by c-martinez** [comment]
Ah, that explains it :-) thanks @weaverbel

**Comment by weaverbel** [comment]
All sorted
