### ISSUE TITLE
Lesson maintainers

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-sql#47]
This lesson has no maintainers listed. Maintainers perform the following tasks:

Maintainers perform a number of important tasks:

- make sure their lesson is consistent with the other Library Carpentry lessons. For example, that the Readme or License pages are correct and consistent (indeed the readme does need a little work https://github.com/data-lessons/library-webscraping/issues/28)
- address any issues that are raised against the lesson
- deal with any pull requests that are made for the lesson.
- after a lesson is taught, make sure that suggestions for improvement from learners and instructors are integrated
- as this is a new lesson, helping it get through the (new) incubator process https://github.com/data-lessons/librarycarpentry/issues/22
- and, ideally, keep up with general Library Carpentry chatter at https://gitter.im/weaverbel/LibraryCarpentry

The lesson needs two maintainers, but more the merrier, especially if we can ensure a good mix of timezones. Anyone up for it?

**Comment by drjwbaker** [comment]
Pinging @icecjan @steltenpower @amsichani @thegsi @elainewong: I see you all worked on this during or since the sprint. Do any of you have enough love for this lesson to help keep it going?

**Comment by steltenpower** [comment]
I'm hoping to invest some time into the carpentries later this year, but lack time for now

**Comment by drjwbaker** [comment]
@steltenpower Well in that case we look forward to seeing you around later in the year!

**Comment by elainewong** [comment]
I can help out.

**Comment by drjwbaker** [comment]
@elainewong Thank you! If you could add yourself to the README as per https://github.com/data-lessons/library-shell/blob/gh-pages/README.md that would be super helpful. Now to find one or two more folks willing to chip in!

**Comment by icecjan** [comment]
I'm happy to help too.

**Comment by elainewong** [comment]
@icecjan awesome! Do you want to add yourself to the README (instructions above) and we can coordinate a time to get together and figure out a game plan to tackle all the outstanding issues?

**Comment by drjwbaker** [comment]
:)

**Comment by icecjan** [comment]
@elainewong OK done. I'm at a conference next week and will have time to get together after! Let's chat on Gitter :)
