### ISSUE TITLE
Handout

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-sql#50]
This lesson might benefit from making a handout of reference materials.

To do this add detail of commands/terminology under the keypoints headers for each lesson: for example, https://github.com/data-lessons/library-data-intro/blob/gh-pages/_episodes/04-regular-expressions.md. This effectively then builds a handout at - for example http://data-lessons.github.io/library-data-intro/reference/ - which can be printed out in advance of the session (librarians love handouts!)

Make sure you make a note of this in your Instructor Notes https://github.com/data-lessons/library-sql/issues/49

**Comment by drjwbaker** [comment]
We have a request for a workshop in Italy in September. The workshop will be lead in English with Italian helpers. To make this work they are asking for there to be a handout in English that can be translated into Italian.

Any chance some can action this work to be done by mid August so they can get the translation work done for September?

I suspect having stable and detailed handouts is a good model for extending out reach to librarians who don't work in English (translating everything is not something every workshop can handle).

**Comment by drjwbaker** [comment]
Further to the above, maintainers @jelainewong @icecjan: I'm running a LC workhop in Padua with @danmichaelo in 14-15 September. They've asked if we can get handouts for the lessons in place so they can translate them for the workshop (they want to translate the handouts only, not the lessons!). This is one of the lessons we'll use. This lesson doesn't have a handout\cheatsheet (like, for example, http://data-lessons.github.io/library-data-intro/reference/) Are there some bits from this lesson that can be quickly turned into one and - if so - any chance you could take a look this week? (w/c 31 July)

**Comment by icecjan** [comment]
@drjwbaker @elainewong I'm happy to have a go at this late this week/weekend, if that's not too late.

**Comment by drjwbaker** [comment]
@icecjan Perfect! Not too late at all. Just a little cheat sheet of things to remember would be helpful.

**Comment by icecjan** [comment]
here we go! :) #56
